/**
 * Miximus CosmWasm Contract
 *
 * zkSNARK-based mixer for Cosmos SDK chains (ATOM, LUNA/Terra, OSMO, etc.)
 * Deployed via CosmWasm on any Cosmos chain that supports it.
 *
 * Supported chains: Cosmos Hub (ATOM), Terra (LUNA), Osmosis, Juno, etc.
 *
 * MiMC hash: 91 rounds, x^7 exponent, BN254 scalar field, keccak256 round constants,
 * Miyaguchi-Preneel compression — matching the ethsnarks C++ circuit exactly.
 *
 * Groth16 verification: oracle-based attestation (CosmWasm lacks native BN254 precompiles).
 */

use cosmwasm_std::{
    entry_point, to_json_binary, Addr, BankMsg, Binary, Coin, CosmosMsg, Deps, DepsMut, Env,
    MessageInfo, Response, StdError, StdResult, Uint128, Uint256,
};
use cw_storage_plus::{Item, Map};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use tiny_keccak::{Hasher, Keccak};

// =========================================================================
//                              CONSTANTS
// =========================================================================

pub const TREE_DEPTH: usize = 29;
pub const MAX_LEAVES: u64 = 1u64 << TREE_DEPTH; // 2^29

/// BN254 scalar field modulus: r = 21888242871839275222246405745257275088548364400416034343698204186575808495617
/// All MiMC field arithmetic is performed modulo this prime.
const SCALAR_FIELD_STR: &str =
    "21888242871839275222246405745257275088548364400416034343698204186575808495617";

/// Number of MiMC cipher rounds, matching the ethsnarks C++ circuit.
const MIMC_ROUNDS: usize = 91;

/// Level-specific IVs for the Merkle tree hash at each depth level.
/// These are identical across all chain implementations (EVM, Tron, Solana, etc.)
/// and are generated by the ethsnarks C++ circuit's `merkle_tree_IVs()`.
const LEVEL_IVS: [&str; 29] = [
    "149674538925118052205057075966660054952481571156186698930522557832224430770",
    "9670701465464311903249220692483401938888498641874948577387207195814981706974",
    "18318710344500308168304415114839554107298291987930233567781901093928276468271",
    "6597209388525824933845812104623007130464197923269180086306970975123437805179",
    "21720956803147356712695575768577036859892220417043839172295094119877855004262",
    "10330261616520855230513677034606076056972336573153777401182178891807369896722",
    "17466547730316258748333298168566143799241073466140136663575045164199607937939",
    "18881017304615283094648494495339883533502299318365959655029893746755475886610",
    "21580915712563378725413940003372103925756594604076607277692074507345076595494",
    "12316305934357579015754723412431647910012873427291630993042374701002287130550",
    "18905410889238873726515380969411495891004493295170115920825550288019118582494",
    "12819107342879320352602391015489840916114959026915005817918724958237245903353",
    "8245796392944118634696709403074300923517437202166861682117022548371601758802",
    "16953062784314687781686527153155644849196472783922227794465158787843281909585",
    "19346880451250915556764413197424554385509847473349107460608536657852472800734",
    "14486794857958402714787584825989957493343996287314210390323617462452254101347",
    "11127491343750635061768291849689189917973916562037173191089384809465548650641",
    "12217916643258751952878742936579902345100885664187835381214622522318889050675",
    "722025110834410790007814375535296040832778338853544117497481480537806506496",
    "15115624438829798766134408951193645901537753720219896384705782209102859383951",
    "11495230981884427516908372448237146604382590904456048258839160861769955046544",
    "16867999085723044773810250829569850875786210932876177117428755424200948460050",
    "1884116508014449609846749684134533293456072152192763829918284704109129550542",
    "14643335163846663204197941112945447472862168442334003800621296569318670799451",
    "1933387276732345916104540506251808516402995586485132246682941535467305930334",
    "7286414555941977227951257572976885370489143210539802284740420664558593616067",
    "16932161189449419608528042274282099409408565503929504242784173714823499212410",
    "16562533130736679030886586765487416082772837813468081467237161865787494093536",
    "6037428193077828806710267464232314380014232668931818917272972397574634037180",
];

// =========================================================================
//                              STATE
// =========================================================================

pub const CONFIG: Item<Config> = Item::new("config");
pub const NEXT_LEAF_INDEX: Item<u64> = Item::new("next_leaf_index");
pub const CURRENT_ROOT: Item<Vec<u8>> = Item::new("current_root");
pub const NULLIFIERS: Map<Vec<u8>, bool> = Map::new("nullifiers");
pub const ROOTS: Map<Vec<u8>, bool> = Map::new("roots");
/// Proof attestations submitted by the trusted oracle.
/// Key: keccak256(root || nullifier || external_hash || proof_data), Value: true
pub const PROOF_ATTESTATIONS: Map<Vec<u8>, bool> = Map::new("proof_attestations");

/// Full Merkle tree node storage: TREE_NODES[(level, index)] = hash
/// This replaces the old filled_subtrees approach with complete node storage,
/// matching the EVM contract's treeNodes[level][index] pattern.
pub const TREE_NODES: Map<(u32, u64), Vec<u8>> = Map::new("tree_nodes");

/// Zero hashes for each level (precomputed at init, stored for lookups).
/// ZERO_HASHES[level] = the hash of an empty subtree at that level.
pub const ZERO_HASHES: Map<u32, Vec<u8>> = Map::new("zero_hashes");

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct Config {
    pub owner: Addr,
    pub oracle: Addr,
    pub denomination: Uint128,
    pub denom: String, // e.g., "uatom", "uluna"
    pub asset_symbol: String,
    pub vk_data: Vec<u8>,
}

// =========================================================================
//                           MESSAGES
// =========================================================================

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct InstantiateMsg {
    pub denomination: Uint128,
    pub denom: String,
    pub asset_symbol: String,
    pub vk_data: Vec<u8>,
    /// Address of the trusted oracle that submits Groth16 proof attestations
    pub oracle: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ExecuteMsg {
    /// Deposit native tokens into the mixer
    Deposit { leaf_hash: String },
    /// Withdraw using zkSNARK proof (oracle must have pre-attested the proof)
    Withdraw {
        root: String,
        nullifier: String,
        proof: Vec<u8>,
    },
    /// Withdraw via relayer (oracle must have pre-attested the proof)
    WithdrawViaRelayer {
        root: String,
        nullifier: String,
        proof: Vec<u8>,
        recipient: String,
        relayer_fee: Uint128,
    },
    /// Batch withdraw — process up to 5 withdrawals in a single transaction
    BatchWithdraw {
        roots: Vec<String>,
        nullifiers: Vec<String>,
        proofs: Vec<Vec<u8>>,
    },
    /// Submit a Groth16 proof attestation (oracle only).
    /// The oracle verifies the BN254 pairing off-chain and submits the result.
    SubmitProofAttestation {
        root: String,
        nullifier: String,
        external_hash: String,
        proof_hash: String,
    },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum QueryMsg {
    GetRoot {},
    IsSpent { nullifier: String },
    GetConfig {},
    GetPath { leaf_index: u64 },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct RootResponse {
    pub root: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct SpentResponse {
    pub is_spent: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct PathResponse {
    pub path: Vec<String>,
    pub address_bits: Vec<bool>,
}

// =========================================================================
//                 BN254 FIELD ARITHMETIC (using Uint256)
// =========================================================================

/// Parse the BN254 scalar field modulus from its decimal string representation.
fn scalar_field() -> Uint256 {
    Uint256::from_str_prefixed(SCALAR_FIELD_STR).unwrap()
}

/// Parse a decimal string into a Uint256. Used for level IVs and leaf hashes.
fn uint256_from_dec(s: &str) -> Uint256 {
    Uint256::from_str_prefixed(s).unwrap()
}

/// Convert a Uint256 to a 32-byte big-endian representation.
fn uint256_to_bytes(v: &Uint256) -> Vec<u8> {
    // Uint256 stores as big-endian 32 bytes
    let be = v.to_be_bytes();
    be.to_vec()
}

/// Convert 32-byte big-endian bytes to Uint256.
fn bytes_to_uint256(b: &[u8]) -> Uint256 {
    let mut buf = [0u8; 32];
    if b.len() >= 32 {
        buf.copy_from_slice(&b[..32]);
    } else {
        // Left-pad with zeros
        let offset = 32 - b.len();
        buf[offset..].copy_from_slice(b);
    }
    Uint256::from_be_bytes(buf)
}

/// Modular addition: (a + b) mod p
fn addmod(a: Uint256, b: Uint256, p: Uint256) -> Uint256 {
    // Use Uint512 approach: compute in wider space to avoid overflow
    // Uint256::checked_rem handles the mod. We need overflow-safe add.
    // cosmwasm Uint256 wraps on overflow, so we use the formula:
    // if a + b overflows or a + b >= p, result = a + b - p (possibly twice)
    // But Uint256 can hold up to 2^256 - 1, and our field is ~254 bits,
    // so a < p and b < p means a + b < 2p < 2^255, which fits in Uint256.
    let sum = a + b;
    if sum >= p {
        sum - p
    } else {
        sum
    }
}

/// Modular multiplication: (a * b) mod p
/// Since Uint256 * Uint256 can overflow 256 bits, we implement this using
/// the double-and-add (Russian peasant) method on Uint256.
fn mulmod(a: Uint256, b: Uint256, p: Uint256) -> Uint256 {
    if a.is_zero() || b.is_zero() {
        return Uint256::zero();
    }
    if p.is_zero() {
        return Uint256::zero();
    }

    let a = a % p;
    let b = b % p;

    // Use schoolbook multiplication via double-and-add to avoid overflow.
    // Process bits of b from MSB to LSB.
    let b_bytes = b.to_be_bytes();
    let mut result = Uint256::zero();
    let mut base = a;

    // Iterate bits from MSB to LSB
    for byte_idx in 0..32 {
        let byte_val = b_bytes[byte_idx];
        for bit_idx in (0..8).rev() {
            // Double
            result = addmod(result, result, p);
            // Add if bit is set
            if (byte_val >> bit_idx) & 1 == 1 {
                result = addmod(result, base, p);
            }
        }
    }
    let _ = base; // suppress unused warning

    result
}

// =========================================================================
//                    MiMC HASH FUNCTION (BN254 field)
// =========================================================================

/// Compute keccak256 of a 32-byte input, returning 32 bytes.
fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    let mut output = [0u8; 32];
    hasher.update(data);
    hasher.finalize(&mut output);
    output
}

/// Generate MiMC round constants using a keccak256 hash chain.
/// seed = keccak256("mimc"), then c[i] = keccak256(c[i-1])
/// Returns 91 round constants as Uint256 values reduced mod SCALAR_FIELD.
fn mimc_round_constants() -> Vec<Uint256> {
    let p = scalar_field();
    let seed = keccak256(b"mimc");
    let mut constants = Vec::with_capacity(MIMC_ROUNDS);
    let mut current = seed;

    for _ in 0..MIMC_ROUNDS {
        current = keccak256(&current);
        let c = bytes_to_uint256(&current) % p;
        constants.push(c);
    }

    constants
}

/// MiMC-p/p cipher with exponent 7, matching the ethsnarks C++ circuit.
///
/// For each of 91 rounds:
///   t = x + c_i + k  (mod p)
///   x = t^7           (mod p)
/// Final: output = x + k  (mod p)
///
/// Where c_i are keccak256 hash-chain round constants and p is the BN254 scalar field.
fn mimc_cipher(in_x: Uint256, in_k: Uint256) -> Uint256 {
    let p = scalar_field();
    let constants = mimc_round_constants();
    let mut x = in_x % p;
    let k = in_k % p;

    for i in 0..MIMC_ROUNDS {
        // t = x + c_i + k (mod p)
        let t = addmod(addmod(x, constants[i], p), k, p);

        // t^7 = t * (t^2)^3
        let t2 = mulmod(t, t, p);       // t^2
        let t4 = mulmod(t2, t2, p);     // t^4
        let t6 = mulmod(t4, t2, p);     // t^6
        x = mulmod(t6, t, p);           // t^7
    }

    // Final key addition
    addmod(x, k, p)
}

/// MiMC hash using Miyaguchi-Preneel compression, matching ethsnarks MiMC.Hash().
///
/// r starts at iv. For each input x:
///   h = mimc_cipher(x, r)
///   r = r + x + h  (mod p)
///
/// This is the standard Miyaguchi-Preneel construction applied to MiMC.
fn mimc_hash(data: &[Uint256], iv: Uint256) -> Uint256 {
    let p = scalar_field();
    let mut r = iv;

    for x in data {
        let h = mimc_cipher(*x, r);
        r = addmod(addmod(r, *x, p), h, p);
    }

    r
}

/// Convenience: MiMC hash with IV = 0 (used for nullifier hash, pub_hash, leaf hash).
fn mimc_hash_default(data: &[Uint256]) -> Uint256 {
    mimc_hash(data, Uint256::zero())
}

/// MiMC hash with a level-specific IV, used for Merkle tree level hashing.
fn mimc_hash_with_level_iv(data: &[Uint256], level: usize) -> Uint256 {
    let iv = uint256_from_dec(LEVEL_IVS[level]);
    mimc_hash(data, iv)
}

// =========================================================================
//                         ENTRY POINTS
// =========================================================================

#[entry_point]
pub fn instantiate(
    deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {
    let oracle_addr = deps.api.addr_validate(&msg.oracle)?;

    let config = Config {
        owner: info.sender.clone(),
        oracle: oracle_addr,
        denomination: msg.denomination,
        denom: msg.denom,
        asset_symbol: msg.asset_symbol,
        vk_data: msg.vk_data,
    };
    CONFIG.save(deps.storage, &config)?;

    // Initialize the Merkle tree: compute zero hashes for each level and store
    let initial_root = initialize_merkle_tree(deps)?;

    // Store initial root as valid
    ROOTS.save(deps.storage, initial_root.clone(), &true)?;
    CURRENT_ROOT.save(deps.storage, &initial_root)?;
    NEXT_LEAF_INDEX.save(deps.storage, &0u64)?;

    Ok(Response::new()
        .add_attribute("method", "instantiate")
        .add_attribute("owner", info.sender)
        .add_attribute("denomination", msg.denomination))
}

#[entry_point]
pub fn execute(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    msg: ExecuteMsg,
) -> StdResult<Response> {
    match msg {
        ExecuteMsg::Deposit { leaf_hash } => execute_deposit(deps, env, info, leaf_hash),
        ExecuteMsg::Withdraw {
            root,
            nullifier,
            proof,
        } => execute_withdraw(deps, env, info, root, nullifier, proof),
        ExecuteMsg::WithdrawViaRelayer {
            root,
            nullifier,
            proof,
            recipient,
            relayer_fee,
        } => execute_withdraw_via_relayer(
            deps, env, info, root, nullifier, proof, recipient, relayer_fee,
        ),
        ExecuteMsg::BatchWithdraw {
            roots,
            nullifiers,
            proofs,
        } => execute_batch_withdraw(deps, env, info, roots, nullifiers, proofs),
        ExecuteMsg::SubmitProofAttestation {
            root,
            nullifier,
            external_hash,
            proof_hash,
        } => execute_submit_proof_attestation(
            deps, info, root, nullifier, external_hash, proof_hash,
        ),
    }
}

#[entry_point]
pub fn query(deps: Deps, _env: Env, msg: QueryMsg) -> StdResult<Binary> {
    match msg {
        QueryMsg::GetRoot {} => {
            let root = CURRENT_ROOT.load(deps.storage)?;
            to_json_binary(&RootResponse {
                root: hex::encode(&root),
            })
        }
        QueryMsg::IsSpent { nullifier } => {
            let key =
                hex::decode(&nullifier).map_err(|_| StdError::generic_err("Invalid hex"))?;
            let is_spent = NULLIFIERS
                .may_load(deps.storage, key)?
                .unwrap_or(false);
            to_json_binary(&SpentResponse { is_spent })
        }
        QueryMsg::GetConfig {} => {
            let config = CONFIG.load(deps.storage)?;
            to_json_binary(&config)
        }
        QueryMsg::GetPath { leaf_index } => query_get_path(deps, leaf_index),
    }
}

// =========================================================================
//                       EXECUTE HANDLERS
// =========================================================================

fn execute_deposit(
    deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    leaf_hash: String,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;

    // Verify correct amount was sent
    let sent = info
        .funds
        .iter()
        .find(|c| c.denom == config.denom)
        .map(|c| c.amount)
        .unwrap_or(Uint128::zero());

    if sent != config.denomination {
        return Err(StdError::generic_err("Must deposit exact denomination"));
    }

    let leaf_index = NEXT_LEAF_INDEX.load(deps.storage)?;
    if leaf_index >= MAX_LEAVES {
        return Err(StdError::generic_err("Merkle tree is full"));
    }

    // Parse leaf hash as a decimal string (field element) and convert to 32-byte big-endian
    let leaf_value = uint256_from_dec(&leaf_hash);
    let leaf_bytes = uint256_to_bytes(&leaf_value);

    // Insert leaf into Merkle tree and compute new root
    let new_root = insert_leaf(deps, leaf_index, &leaf_bytes)?;

    // Update state
    NEXT_LEAF_INDEX.save(deps.storage, &(leaf_index + 1))?;
    CURRENT_ROOT.save(deps.storage, &new_root)?;
    ROOTS.save(deps.storage, new_root, &true)?;

    Ok(Response::new()
        .add_attribute("method", "deposit")
        .add_attribute("leaf_index", leaf_index.to_string())
        .add_attribute("leaf_hash", leaf_hash))
}

fn execute_batch_deposit(
    mut deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    leaf_hashes: Vec<String>,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;

    let count = leaf_hashes.len() as u128;
    if count == 0 || count > 20 {
        return Err(StdError::generic_err("Batch size must be 1-20"));
    }

    // Verify total amount sent
    let sent = info
        .funds
        .iter()
        .find(|c| c.denom == config.denom)
        .map(|c| c.amount)
        .unwrap_or(Uint128::zero());

    let total_required = config.denomination * Uint128::from(count);
    if sent != total_required {
        return Err(StdError::generic_err("Must deposit exact total denomination"));
    }

    let mut leaf_index = NEXT_LEAF_INDEX.load(deps.storage)?;
    let start_index = leaf_index;

    for leaf_hash in &leaf_hashes {
        if leaf_index >= MAX_LEAVES {
            return Err(StdError::generic_err("Merkle tree is full"));
        }

        let leaf_value = uint256_from_dec(leaf_hash);
        let leaf_bytes = uint256_to_bytes(&leaf_value);
        let new_root = insert_leaf(deps.branch(), leaf_index, &leaf_bytes)?;

        leaf_index += 1;
        NEXT_LEAF_INDEX.save(deps.storage, &leaf_index)?;
        CURRENT_ROOT.save(deps.storage, &new_root)?;
        ROOTS.save(deps.storage, new_root, &true)?;
    }

    Ok(Response::new()
        .add_attribute("method", "batch_deposit")
        .add_attribute("start_index", start_index.to_string())
        .add_attribute("count", count.to_string()))
}

fn execute_withdraw(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    root: String,
    nullifier: String,
    proof: Vec<u8>,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;
    let recipient = info.sender.clone();

    let nullifier_bytes =
        hex::decode(&nullifier).map_err(|_| StdError::generic_err("Invalid nullifier hex"))?;
    let root_bytes =
        hex::decode(&root).map_err(|_| StdError::generic_err("Invalid root hex"))?;

    // Check nullifier not spent
    if NULLIFIERS
        .may_load(deps.storage, nullifier_bytes.clone())?
        .unwrap_or(false)
    {
        return Err(StdError::generic_err("Cannot double-spend"));
    }

    // Check root is known
    if !ROOTS
        .may_load(deps.storage, root_bytes.clone())?
        .unwrap_or(false)
    {
        return Err(StdError::generic_err("Unknown merkle root"));
    }

    // Compute external hash: sha256(contract_address || recipient) mod SCALAR_FIELD
    let external_hash = compute_external_hash(&env.contract.address, &recipient);

    // Verify proof via oracle attestation
    let is_valid = verify_proof(
        deps.as_ref(),
        &root_bytes,
        &nullifier_bytes,
        &uint256_to_bytes(&external_hash),
        &proof,
    )?;
    if !is_valid {
        return Err(StdError::generic_err("Invalid zkSNARK proof: no oracle attestation found"));
    }

    // Mark nullifier as spent
    NULLIFIERS.save(deps.storage, nullifier_bytes, &true)?;

    // Transfer denomination to recipient
    let transfer_msg = CosmosMsg::Bank(BankMsg::Send {
        to_address: recipient.to_string(),
        amount: vec![Coin {
            denom: config.denom,
            amount: config.denomination,
        }],
    });

    Ok(Response::new()
        .add_message(transfer_msg)
        .add_attribute("method", "withdraw")
        .add_attribute("nullifier", nullifier)
        .add_attribute("recipient", recipient))
}

fn execute_batch_withdraw(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    roots: Vec<String>,
    nullifiers: Vec<String>,
    proofs: Vec<Vec<u8>>,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;
    let recipient = info.sender.clone();
    let count = roots.len();

    if count == 0 || count > 5 {
        return Err(StdError::generic_err("Batch size must be 1-5"));
    }
    if nullifiers.len() != count || proofs.len() != count {
        return Err(StdError::generic_err("Array lengths must match"));
    }

    for i in 0..count {
        let nullifier_bytes = hex::decode(&nullifiers[i])
            .map_err(|_| StdError::generic_err("Invalid nullifier hex"))?;
        let root_bytes = hex::decode(&roots[i])
            .map_err(|_| StdError::generic_err("Invalid root hex"))?;

        // Check nullifier not spent
        if NULLIFIERS
            .may_load(deps.storage, nullifier_bytes.clone())?
            .unwrap_or(false)
        {
            return Err(StdError::generic_err("Cannot double-spend"));
        }

        // Check root is known
        if !ROOTS
            .may_load(deps.storage, root_bytes.clone())?
            .unwrap_or(false)
        {
            return Err(StdError::generic_err("Unknown merkle root"));
        }

        // Compute external hash
        let external_hash = compute_external_hash(&env.contract.address, &recipient);

        // Verify proof via oracle attestation
        let is_valid = verify_proof(
            deps.as_ref(),
            &root_bytes,
            &nullifier_bytes,
            &uint256_to_bytes(&external_hash),
            &proofs[i],
        )?;
        if !is_valid {
            return Err(StdError::generic_err("Invalid zkSNARK proof: no oracle attestation found"));
        }

        // Mark nullifier as spent
        NULLIFIERS.save(deps.storage, nullifier_bytes, &true)?;
    }

    // Transfer total denomination to recipient
    let total_amount = config.denomination * Uint128::from(count as u128);
    let transfer_msg = CosmosMsg::Bank(BankMsg::Send {
        to_address: recipient.to_string(),
        amount: vec![Coin {
            denom: config.denom,
            amount: total_amount,
        }],
    });

    Ok(Response::new()
        .add_message(transfer_msg)
        .add_attribute("method", "batch_withdraw")
        .add_attribute("count", count.to_string())
        .add_attribute("recipient", recipient))
}

fn execute_withdraw_via_relayer(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    root: String,
    nullifier: String,
    proof: Vec<u8>,
    recipient: String,
    relayer_fee: Uint128,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;
    let recipient_addr = deps.api.addr_validate(&recipient)?;

    if relayer_fee >= config.denomination {
        return Err(StdError::generic_err("Fee exceeds denomination"));
    }

    let nullifier_bytes =
        hex::decode(&nullifier).map_err(|_| StdError::generic_err("Invalid nullifier hex"))?;
    let root_bytes =
        hex::decode(&root).map_err(|_| StdError::generic_err("Invalid root hex"))?;

    if NULLIFIERS
        .may_load(deps.storage, nullifier_bytes.clone())?
        .unwrap_or(false)
    {
        return Err(StdError::generic_err("Cannot double-spend"));
    }
    if !ROOTS
        .may_load(deps.storage, root_bytes.clone())?
        .unwrap_or(false)
    {
        return Err(StdError::generic_err("Unknown merkle root"));
    }

    // Compute external hash: sha256(contract_address || recipient) mod SCALAR_FIELD
    let external_hash = compute_external_hash(&env.contract.address, &recipient_addr);

    let is_valid = verify_proof(
        deps.as_ref(),
        &root_bytes,
        &nullifier_bytes,
        &uint256_to_bytes(&external_hash),
        &proof,
    )?;
    if !is_valid {
        return Err(StdError::generic_err("Invalid proof: no oracle attestation found"));
    }

    NULLIFIERS.save(deps.storage, nullifier_bytes, &true)?;

    let mut messages: Vec<CosmosMsg> = vec![];

    // Relayer fee
    if !relayer_fee.is_zero() {
        messages.push(CosmosMsg::Bank(BankMsg::Send {
            to_address: info.sender.to_string(),
            amount: vec![Coin {
                denom: config.denom.clone(),
                amount: relayer_fee,
            }],
        }));
    }

    // Recipient gets remainder
    let remaining = config.denomination - relayer_fee;
    messages.push(CosmosMsg::Bank(BankMsg::Send {
        to_address: recipient,
        amount: vec![Coin {
            denom: config.denom,
            amount: remaining,
        }],
    }));

    Ok(Response::new()
        .add_messages(messages)
        .add_attribute("method", "withdraw_via_relayer")
        .add_attribute("nullifier", nullifier))
}

/// Submit a Groth16 proof attestation. Only the trusted oracle can call this.
///
/// The oracle performs the full BN254 pairing check off-chain (using a Groth16 verifier
/// library such as snarkjs, ethsnarks, or bellman) and then submits an attestation
/// that the proof is valid for the given public inputs.
///
/// The attestation key is keccak256(root || nullifier || external_hash || proof_hash),
/// which uniquely identifies the proof + public inputs combination.
fn execute_submit_proof_attestation(
    deps: DepsMut,
    info: MessageInfo,
    root: String,
    nullifier: String,
    external_hash: String,
    proof_hash: String,
) -> StdResult<Response> {
    let config = CONFIG.load(deps.storage)?;

    // Only the trusted oracle may submit attestations
    if info.sender != config.oracle {
        return Err(StdError::generic_err(
            "Unauthorized: only the oracle can submit proof attestations",
        ));
    }

    let root_bytes =
        hex::decode(&root).map_err(|_| StdError::generic_err("Invalid root hex"))?;
    let nullifier_bytes =
        hex::decode(&nullifier).map_err(|_| StdError::generic_err("Invalid nullifier hex"))?;
    let external_hash_bytes = hex::decode(&external_hash)
        .map_err(|_| StdError::generic_err("Invalid external_hash hex"))?;
    let proof_hash_bytes =
        hex::decode(&proof_hash).map_err(|_| StdError::generic_err("Invalid proof_hash hex"))?;

    // Compute attestation key: keccak256(root || nullifier || external_hash || proof_hash)
    let attestation_key = compute_attestation_key(
        &root_bytes,
        &nullifier_bytes,
        &external_hash_bytes,
        &proof_hash_bytes,
    );

    PROOF_ATTESTATIONS.save(deps.storage, attestation_key.to_vec(), &true)?;

    Ok(Response::new()
        .add_attribute("method", "submit_proof_attestation")
        .add_attribute("root", root)
        .add_attribute("nullifier", nullifier))
}

// =========================================================================
//                         QUERY HANDLERS
// =========================================================================

fn query_get_path(deps: Deps, leaf_index: u64) -> StdResult<Binary> {
    let next_leaf = NEXT_LEAF_INDEX.load(deps.storage)?;
    if leaf_index >= next_leaf {
        return Err(StdError::generic_err("Leaf not yet inserted"));
    }

    let mut path = Vec::with_capacity(TREE_DEPTH);
    let mut address_bits = Vec::with_capacity(TREE_DEPTH);
    let mut idx = leaf_index;

    for level in 0..TREE_DEPTH {
        let is_right = (idx & 1) == 1;
        address_bits.push(is_right);
        let sibling_idx = idx ^ 1;
        let sibling = get_node(deps, level as u32, sibling_idx)?;
        let sibling_value = bytes_to_uint256(&sibling);
        path.push(sibling_value.to_string());
        idx >>= 1;
    }

    to_json_binary(&PathResponse {
        path,
        address_bits,
    })
}

// =========================================================================
//                 MERKLE TREE OPERATIONS (full node storage)
// =========================================================================

/// Initialize the Merkle tree by computing zero hashes for each level.
///
/// zero_hash[0] = 0 (empty leaf)
/// zero_hash[i] = MiMC_IV(level_i)(zero_hash[i-1], zero_hash[i-1])
///
/// The root of a completely empty tree is the final zero hash.
fn initialize_merkle_tree(deps: DepsMut) -> StdResult<Vec<u8>> {
    let mut zero = Uint256::zero();

    for level in 0..TREE_DEPTH {
        let zero_bytes = uint256_to_bytes(&zero);
        ZERO_HASHES.save(deps.storage, level as u32, &zero_bytes)?;

        // Hash two zero children at this level to get zero hash for next level
        let data = [zero, zero];
        zero = mimc_hash_with_level_iv(&data, level);
    }

    // The final zero is the root of a completely empty tree
    let root_bytes = uint256_to_bytes(&zero);
    Ok(root_bytes)
}

/// Insert a leaf into the Merkle tree at the given index, updating all
/// ancestor nodes up to the root. Returns the new root hash as bytes.
///
/// This stores EVERY computed node in TREE_NODES, matching the EVM contract's
/// treeNodes[level][index] = hash pattern.
fn insert_leaf(deps: DepsMut, leaf_index: u64, leaf_bytes: &[u8]) -> StdResult<Vec<u8>> {
    // Store the leaf at level 0
    TREE_NODES.save(deps.storage, (0u32, leaf_index), &leaf_bytes.to_vec())?;

    let mut current_node = bytes_to_uint256(leaf_bytes);
    let mut idx = leaf_index;

    for level in 0..TREE_DEPTH {
        let parent_idx = idx / 2;

        let (left, right) = if idx % 2 == 0 {
            // Current node is left child; sibling is right
            let sibling = get_node(deps.as_ref(), level as u32, idx + 1)?;
            (current_node, bytes_to_uint256(&sibling))
        } else {
            // Current node is right child; sibling is left
            let sibling = get_node(deps.as_ref(), level as u32, idx - 1)?;
            (bytes_to_uint256(&sibling), current_node)
        };

        let data = [left, right];
        current_node = mimc_hash_with_level_iv(&data, level);

        // Store the parent node at level+1
        let parent_bytes = uint256_to_bytes(&current_node);
        TREE_NODES.save(deps.storage, ((level + 1) as u32, parent_idx), &parent_bytes)?;

        idx = parent_idx;
    }

    Ok(uint256_to_bytes(&current_node))
}

/// Retrieve a node from the Merkle tree. If the node has not been stored
/// (i.e., it was never part of an insertion path), return the zero hash
/// for that level.
fn get_node(deps: Deps, level: u32, index: u64) -> StdResult<Vec<u8>> {
    match TREE_NODES.may_load(deps.storage, (level, index))? {
        Some(val) => Ok(val),
        None => {
            // Return the zero hash for this level (uninitialized node)
            ZERO_HASHES.load(deps.storage, level)
        }
    }
}

// =========================================================================
//                    PROOF VERIFICATION (oracle-based)
// =========================================================================

/// Compute external_hash = sha256(contract_address || recipient) mod SCALAR_FIELD.
/// This matches the EVM contract's getExtHash() which uses sha256.
fn compute_external_hash(contract_addr: &Addr, recipient: &Addr) -> Uint256 {
    use sha2::{Digest, Sha256};

    let p = scalar_field();
    let mut hasher = Sha256::new();
    hasher.update(contract_addr.as_bytes());
    hasher.update(recipient.as_bytes());
    let hash = hasher.finalize();
    bytes_to_uint256(&hash) % p
}

/// Compute the attestation key: keccak256(root || nullifier || external_hash || proof_data).
/// This key uniquely binds the oracle's attestation to a specific proof and public inputs.
fn compute_attestation_key(
    root: &[u8],
    nullifier: &[u8],
    external_hash: &[u8],
    proof_data: &[u8],
) -> [u8; 32] {
    let mut data = Vec::with_capacity(root.len() + nullifier.len() + external_hash.len() + proof_data.len());
    data.extend_from_slice(root);
    data.extend_from_slice(nullifier);
    data.extend_from_slice(external_hash);
    data.extend_from_slice(proof_data);
    keccak256(&data)
}

/// Verify a zkSNARK proof by checking if the trusted oracle has submitted
/// an attestation for this specific proof and public inputs.
///
/// CosmWasm does not have native BN254 pairing precompiles, so we cannot
/// perform on-chain Groth16 verification. Instead, a trusted oracle performs
/// the pairing check off-chain and submits an attestation to the contract.
///
/// The verification flow:
/// 1. User generates a Groth16 proof off-chain
/// 2. User submits the proof to the trusted oracle service
/// 3. Oracle verifies the BN254 pairing check (using snarkjs/bellman/etc.)
/// 4. If valid, oracle calls SubmitProofAttestation with the public inputs + proof hash
/// 5. User calls Withdraw/WithdrawViaRelayer; this function checks the attestation exists
fn verify_proof(
    deps: Deps,
    root: &[u8],
    nullifier: &[u8],
    external_hash: &[u8],
    proof: &[u8],
) -> StdResult<bool> {
    // Hash the proof data to get a compact key component
    let proof_hash = keccak256(proof);

    // Compute the attestation key
    let attestation_key = compute_attestation_key(root, nullifier, external_hash, &proof_hash);

    // Check if the oracle has attested this proof
    let attested = PROOF_ATTESTATIONS
        .may_load(deps.storage, attestation_key.to_vec())?
        .unwrap_or(false);

    Ok(attested)
}
